# 10.30 homework

# 1.简要概括 k-近邻算法的原理，优缺点:
### 原理：你的训练模型已经输入了很多样本集（假定 n），都标记好了相应的“类别”信息，当一个新的数据输入到模型里，再这n条记录中选择与新数据记录“距离”最近得k个点，这k个点大多数是哪个类别，那么新的记录就是那个类别的。
### 优点：精度高，不受异常值影响。
### 缺点：复杂度高，计算耗费时间多

# 2.使用 k­近邻算法改进网站的配对效果”完整代码键入jupyter notebook，并添加详细注释。若有可能，自己可以优化该代码

In [1]:
import numpy as np
import sys
x = [1,2,3,4,5]
# print(x[2:])
xx = [
    [1,2,3],[10,20,30],[6,7,8]
]
xx = np.array([
    [1,2,3,4,5],
    [10,20,30,40,50],
    [66,77,88,99,0]
])  
print(xx[:,0:1])
# 所有行的第0个数据
print(xx[2:2,:])
# 所有行的第2个数据
print(xx[0,0:4])
# 所有行的第 0-3（index）数值 

print(xx[0:2,0:4])
# 所有行的第 0-3（index）数值 

y = np.zeros((3, 3))
for i in range(3):
    y[i,:] = xx[i,0:3]
print(xx)
print(y)

# 以上 切片操作自学

[[ 1]
 [10]
 [66]]
[]
[1 2 3 4]
[[ 1  2  3  4]
 [10 20 30 40]]
[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [66 77 88 99  0]]
[[ 1.  2.  3.]
 [10. 20. 30.]
 [66. 77. 88.]]


In [2]:
# 导入程序所需要的模块
import numpy as np
import operator

# 定义数据集 导入数据函数
功能就是读取文件 函数最后返回特征矩阵和输出标签 显然是监督学习类型

In [3]:
def file2matrix(filename):
    love_dic = {'very':3,
                'normal':2,
                'boring':1}
    fr = open(filename) #打开文件
    arrayOfLines = fr.readlines()#逐行读取
    numberOfLines = len(arrayOfLines)#得到文件的行数
    returnMat = np.zeros( (numberOfLines,3) )
    classLabelVector = []
    index = 0
    for line in arrayOfLines:
        line = line.strip()#删除首尾空串
        listFromLine = line.split('\t')#数据都是以\t划分间隔的
        returnMat[index,0:3] = listFromLine[0:3]#index行，填充listFromLine的012
        if(listFromLine[-1].isdigit()):
            classLabelVector.append(int(listFromLine[-1]))
        else:
            classLabelVector.append(love_dic.get(listFromLine[-1]))
# 对于每一条数据都要  加到矩阵里面 并添加标签
        index += 1
    return returnMat,classLabelVector

# 定义数据标准化函数

In [4]:
def autoNorm(dataSet):
    minVals = dataSet.min(0)
    maxVals = dataSet.max(0)
    ranges = maxVals - minVals
    normDataSet = np.zeros(np.shape(dataSet))
    m = dataSet.shape[0]
#  t = sum( (x - x.)^2 )
#  t = sqrt(t) 
    normDataSet = dataSet - np.tile(minVals, (m, 1))
    normDataSet = normDataSet/np.tile(ranges, (m, 1))  
    # normDataSet值被限定在[0,1]之间
    return normDataSet, ranges, minVals

In [5]:
dataSet = np.array([
    [1,2,3,4,5],
    [10,20,30,40,50],
    [66,77,88,99,110]
])
print(dataSet.sum(axis=1).sum(axis=0))
# 先对行求和,再对列求和
x1 = dataSet.min(0)
x2 = dataSet.min(1)
print(x1,x2)
minVals = dataSet.min(0)
maxVals = dataSet.max(0)
ranges = maxVals - minVals
normDataSet = np.zeros(np.shape(dataSet))
m = dataSet.shape[0]
tt = np.tile(minVals, (m, 1))
normDataSet = dataSet - tt
normDataSet = normDataSet/np.tile(ranges, (m, 1))  
# normDataSet值被限定在[0,1]之间




605
[1 2 3 4 5] [ 1 10 66]


In [6]:
# x = np.array([
#        [1,2,3],
#     [0,0,0],
#     [11,22,33]
# ])
# print(np.tile(x,(10,1)))
# 第一个维度 *10 第二个维度*1
# x = np.array([
#     [1,2,3],
#     [0,0,0],
#     [11,22,33]
# ])
# print(np.tile(x,(10,2)))
# 第一个维度 *10 第二个维度*2

# dataSet = np.array([
#     [10,20,30],
#     [11,21,31],
#     [21,22,23]
# ])
# np.tile(x,(3,1))-dataSet


In [7]:
# inX 测试集 dataSet训练集 labels 训练标签 k 取前k个
def classify0(inX, dataSet, labels, k):
    dataSize = dataSet.shape[0]
    # 使用标准差计算距离    
    t = np.tile(inX,(dataSize,1))-dataSet
    t = t.sum(axis=1)
    distances = t**0.5
    # 计算结束
    sorterDisIndicies = distances.argsort() #返回排序索引从小到大
    classCount = {}   # 字典存储k近邻不同label出现的次数
    for i in range(k):
        voteIlabel = labels[sorterDisIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel, 0) + 1    # 对应label加1，classCount中若无此key，则默认为0
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)    # operator.itemgetter 获取对象的哪个维度的数据
    return sortedClassCount[0][0]    # 返回k近邻中所属类别最多的哪一类

# 定义 k 近邻算法

In [8]:
def datingClassTest():
    hoRatio = 0.1     #整个数据集的10%用来测试
    datingDataMat, datingLabels = file2matrix('datingTestSet2.txt')       #导入数据集
#     normMat, ranges, minVals = autoNorm(datingDataMat)    # 所有特征归一化
#     m = normMat.shape[0]    # 样本个数
    m = datingDataMat.shape[0]
    numTestVecs = int(m*hoRatio)    # 测试样本个数
    errorCount = 0.0
    for i in range(numTestVecs):
        classifierResult = classify0(datingDataMat[i, :], datingDataMat[numTestVecs:m, :], datingLabels[numTestVecs:m], 3)
        print("the classifier came back with: %d, the real answer is: %d" % (classifierResult, datingLabels[i]))
        if (classifierResult != datingLabels[i]): errorCount += 1.0
    print("the total error rate is: %f" % (errorCount / float(numTestVecs)))    # 打印错误率
    print(errorCount)    # 打印错误个数

In [ ]:
datingClassTest()

the classifier came back with: 3, the real answer is: 3
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 3, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 3
the classifier came back with: 3, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 3, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answe

e:\ana\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in sqrt
  import sys


In [ ]:
def auto_classify_method():
    datingDataMat, datingLabels = file2matrix('datingTestSet2.txt')       #导入数据集
    normMat, ranges, minVals = autoNorm(datingDataMat)    # 所有特征归一化
    m = normMat.shape[0]
    while True:
        Tag = 0
        var1 = input("fly gosts time")
        var2 = input("playing time")
        var3 = input("dessert weight")
        try:
            inputx = np.array([float(var1),float(var2),float(var3)])
        except:
            print("input again")
            Tag = 1
            pass
        
        if Tag == 0:
            print(inputx)
#         classifierResult = classify0((inputx-minVals)/(ranges-minVals),normMat[0:m, :], datingLabels[0:m], 3)
            classifierResult = classify0(inputx,datingDataMat[0:m, :], datingLabels[0:m], 3)
            print("maybe ...: ",classifierResult)

In [ ]:
auto_classify_method()

fly gosts timea
playing timea
dessert weighta
input again
fly gosts time6487	
playing time3.540265	
dessert weight0.822483	


e:\ana\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in sqrt
  import sys


[6.487000e+03 3.540265e+00 8.224830e-01]
maybe ...:  2
fly gosts time0.822483
playing time12.591889	
dessert weight0.9	
[ 0.822483 12.591889  0.9     ]
maybe ...:  2
fly gosts time0.822483
playing time1
dessert weight1
[0.822483 1.       1.      ]
maybe ...:  2
fly gosts time1
playing time1
dessert weight1
[1. 1. 1.]
maybe ...:  2
fly gosts time33553	
playing time12.591889
dessert weight0.9
[3.3553000e+04 1.2591889e+01 9.0000000e-01]
maybe ...:  3
